spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sandbox?autoreconnect=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

